---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nodejs
    - npm

- name: Install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present